Agregado actions a Edit
janis-commerce/view-schema-validator pull request #274
Opened 2023-05-12 15:49 UTC by FranciscoZapa

… remoteActions no ambos

## Link al ticket
- [Link](https://janiscommerce.atlassian.net/browse/JMV-2958)
## Descripción del requerimiento
- Se necesita crear una nueva prop Actions que reemplace pero no elimine las RemoteActions. 
## Descripción de la solución
- Se agrego un nuevo schema para Actions que reutiliza la logica de massiveActions dejando la propiedad getEndpointParameters en false para que tome tanto valores static como dynamic, se creo un archivo para el schema remoteActions para poder reutilizarlo en el condicional agregado, dichos condicional valida si existe actions y cuando es asi impide que se reciba remoteActions y viceversa para que de esta forma solo uno de los dos sea aceptado, en ningun caso ambos. Se agrego actions a los mocks de prueba comentando remoteActions para no perder la info de como se debe implementar. Se utilizo allOf para que siempre deban cumplirse los dos condicionales.
## Cómo se puede probar?
- Descomentando remoteActions en test/mocks/schemas/Edit.yml para dejar ambos y ejecutando el comando  node index.js validate -i tests/mocks/schemas/edit.yml para validar que da error, luego quitando ya sea actions o remoteActions para validar que si los recibe por separado.
## Link a la documentación
- 
## Datos extra a tener en cuenta
- 
## Changelog
``` Agregado actions al schema de Edit, validando que solo pueda estar actions o remoteActions, siendo excluyente el uno del otro.  
### Added
- Agregado actions al schema de Edit
- Validado que solo pueda tenerse actions o remoteActions en schema de Edit, en ningun caso ambos, siendo ambos opcionales.
- Creado archivo para schema remoteActions
- Creado archivo para schema actions
### Changed
- 
### Fixed
- 
### Deprecated
- 
### Removed
- 
```

2023-05-15 16:45 UTC, Mauroskyer approved these changes

2023-05-15 17:35 UTC, fiorafran approved these changes

2023-05-17 14:58 UTC, colomfernando requested changes
Deje comentarios para corregir

2023-05-17 14:58 UTC, colomfernando commented on lib/schemas/edit/schema.js
>  const { properties, if: conditonal, then: isTrue, else: isFalse } = require('../edit-new/schema');
quedo conditonal y es conditional @FranciscoZapa

2023-05-17 14:58 UTC, colomfernando commented on lib/schemas/common/actions.js
> +	minProperties: 1
la key minPropertie no le veo mucho sentido dado que necesitamos que se defina o actions o source por lo menos

2023-05-17 14:58 UTC, colomfernando commented on tests/mocks/schemas/edit.yml
> +#remoteActions:
Agregar los distintos test para actions o remoteActions

2023-05-17 18:29 UTC, FranciscoZapa commented
Correcciones listas

2023-05-18 16:02 UTC, FranciscoZapa commented
Probe tambien con redirect para probar si rompia pero si funciona bien
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/d16cd71c-d098-43e0-addd-3dfb79087af9)

2023-05-18 20:33 UTC, colomfernando commented
@FranciscoZapa actualizar la descripcion con los cambios que te pedi y como lo solucionaste

2023-05-18 20:53 UTC, colomfernando commented
@FranciscoZapa en base a lo charlado, la key actions dentro de action, pasaria a ser staticActions

2023-05-18 21:55 UTC, FranciscoZapa commented
Correcciones listas

2023-05-19 16:52 UTC, Mauroskyer approved these changes

2023-05-19 18:35 UTC, FranciscoZapa commented
> nose como la ven de cambiarlo ahora, pero los siguientes test te quedaron los target: query
> 
> * edit-with-remote-actions.yml
> * edit-with-actions-source.yml
> * edit-with-actions-static.yml
> 
> El resto lo veo bien
Listo Fiora ahi lo corregi

2023-05-19 20:34 UTC, fiorafran approved these changes

2023-06-07 19:58 UTC, merged