new prop columnMatch and deprecate attributes
janis-commerce/view-schema-validator pull request #283
Opened 2023-09-12 22:38 UTC by fiorafran

## Link al ticket
https://janiscommerce.atlassian.net/browse/JMV-3120

## Descripción del requerimiento
No se esta pudiendo aplicar el ordenamiento por columnas debido a que existen varios fields en la columna (fieldList)
Por lo que necesitamos que la columna pueda detectar/encontrar el field necesario/correspondiente para poder aplicar el ordenamiento

## Descripción de la solución
Agregamos una nueva props a los fields llamada columnMatch para que con esta prop la columna pueda encontrar el sortableField con el que quiere ordenar

## Cómo se puede probar?
correr los test, verificar que pasen.
Eliminar la prop de los schemas y probar que sigan funcionando.

## Link a la documentación
Pendiente documentar prop nueva

## Datos extra a tener en cuenta
-
## Changelog
```
### Added
- Prop `columnMatch` to fields

2023-09-13 20:34 UTC, dgiannico19 approved these changes
Probé enviando los test y pasan, 
borrando la prop en ambos schemas y pasa bien, 
borrando solamente la prop en fields rompe ya que esta la prop en los schemas y no en fields, 
borrandola de todos lados continua bien

2023-09-14 19:54 UTC, FranciscoZapa requested changes
@fiorafran te deje un comentario de una tonteria que encontre con el nombre de la clase, lo demas lo veo todo perfecto

2023-09-14 19:54 UTC, FranciscoZapa commented on lib/deprecation-validators/attributes-deprecation.js
> +module.exports = class RemoteActionsDeprecation {
me parece que estaría bueno cambiarle el nombre a la clase por AttributesDeprecation, porque no tendría que ver con los remoteActions

2023-09-18 13:18 UTC, fiorafran commented on lib/deprecation-validators/attributes-deprecation.js
> +module.exports = class RemoteActionsDeprecation {
uh se me paso de largo

2023-09-18 13:39 UTC, FranciscoZapa approved these changes

2023-09-18 21:40 UTC, colomfernando approved these changes

2023-09-18 21:44 UTC, merged