redirect validator on create
janis-commerce/view-schema-validator pull request #288
Opened 2023-11-29 18:34 UTC by dgiannico19

## Link al ticket
- https://janiscommerce.atlassian.net/browse/JMV-2880
## Descripción del requerimiento
- Se necesita validar que cuando exista la prop redirect, no sea necesario enviar el target en la pagina new

## Descripción de la solución
- Se agregaron nuevos test para el caso del new con redirect
- Cuando existe redirect, no debe ser requerido el campo target, si lo borramos debería mantenerse todo funcionando a la normalidad

## Cómo se puede probar?
- Ingresando a la rama y ejecutando los test
- Otras pruebas posibles: 
En tests/mocks/schemas/new.yml y tests/mocks/schemas/new-with-min-max-input.yml, borrar los target, agregar en su lugar lo siguiente:
```
redirect:
  source:
    service: conversation
    namespace: template
    method: browse

```
ademas, en tests/mocks/schemas/expected/new.json borrar la prop "target" y agregar lo sig:
 ```
"redirect": {
    "source": {
      "service": "conversation",
      "namespace": "template",
      "method": "browse"
    }
  },
```
Siempre ejecutar los test, deberían dar todos correctos

## Link a la documentación
- https://janiscommerce.atlassian.net/wiki/spaces/JMV/pages/2225864790/Edit-Create
## Datos extra a tener en cuenta
-
## Changelog
```
### Added
- Add required validation on taget prop when exist redirect prop
```

2023-11-29 19:46 UTC, FranciscoZapa commented
Ahi probe corriendo los test y funciona bien 
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/8de6f5e0-e64d-4918-8cfe-80bf40e5eba8)

Tambien probe quitando el redirect y esto hace que sea necesario agregarle sections y target para que funcione bien lo que es correcto
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/110a1621-c48a-48df-977d-76f1209de1eb)

2023-11-29 19:47 UTC, FranciscoZapa approved these changes
Funciona correctamente, mas arriba dejo evidencia de las pruebas realizadas

2023-11-30 17:16 UTC, colomfernando requested changes

2023-11-30 17:16 UTC, colomfernando commented on lib/schemas/new/schema.js
> -	else: { required: [...newEditSchema.else.required, 'target'] }
es correcto, lo que esta pasando ahora es que target que es requerido en los create, ahora no lo es..Hay que revisar esto @dgiannico19

2023-11-30 17:46 UTC, fiorafran commented on lib/schemas/new/schema.js
> -	else: { required: [...newEditSchema.else.required, 'target'] }
por eso justamente, el target es requerido para el new, sino con esto habilitamos que puedan subir un schema new sin target, lo cual esta mal porque no van a tener a donde mandar la data.

2023-12-04 14:35 UTC, FranciscoZapa requested changes
@dgiannico19 no esta funcionando bien, ahi te deje un comentario con pruebas que hice y un cambio que lo hace funcionar

2023-12-04 19:29 UTC, dgiannico19 commented
Corregido listo para revisar @FranciscoZapa

2023-12-04 22:33 UTC, FranciscoZapa commented
Funciona todo correctamente
Quitando redirect pide target y sections 
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/13ff2e38-f227-4b21-b275-d7503e5aff50)
Cuando esta redirect permite no agregar target ni sections
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/0aa048b7-a27a-4eab-a6c5-896f8b5cd4ee)
Si falta target o sections rompe que es correcto
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/9a212b56-679b-4187-bcaa-317e46c0ccbd)
![image](https://github.com/janis-commerce/view-schema-validator/assets/7831086/44ae79e4-a26b-4f74-bb9d-8a96d0155422)

2023-12-04 22:33 UTC, FranciscoZapa approved these changes
Aprobado, arriba dejo evidencia

2023-12-07 13:50 UTC, fiorafran commented
Me esta rompiendo los test:
Si pasa solo con redirect, pero cuando saco redirect y agrego sections y target me rompe.

2023-12-14 17:01 UTC, fiorafran approved these changes
Pasa los test con el redirect.
Si quito redirect, rompe pidiendo las props requeridas.

![image](https://github.com/janis-commerce/view-schema-validator/assets/80725782/c47c6e04-5efd-45c5-9ed6-c6dd20e050f4)

![image](https://github.com/janis-commerce/view-schema-validator/assets/80725782/2958de87-bfa4-4ec7-8e61-a7b027c7f220)

Si agrego las props requeridas pasa los test.

2023-12-14 18:35 UTC, Mauroskyer commented
Probando con test npm run test con sus redirect.
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/50c90a3e-e897-4e51-bcb2-00fbb061e393)

Al quitar el redirect esta mandando bien los errores de las sections.
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/77f6775e-ea35-45ce-bc39-fc9baf7485d1)

Sin redirect con target y sections.
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/71e9bbb7-e727-4c3d-8f13-07e79634a1cb)

Sin redirect y sin sections.
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/ee3c77a1-72d8-4bcf-8da3-57f47a15483d)

schema new sin redirect. 
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/bae30fcf-195e-478f-a436-be68e1dbe82d)

schema new sin redirect y con target.

![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/5db43e8b-7229-4bfb-aa7e-ccef6e1cd1b6)

schema Browse con redirect. 
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/2cb2ea8d-fc7c-4bb5-9365-ba4dbbdb7f40)


Schema Browse sin redirect muestra bien los errores del source y fields.
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/601bea4e-85c3-4754-8eb0-1ea5ddfd26e1)

Schema Browse sin source y sin redirect. 
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/92e6ab59-57f4-469c-8389-e4e1a16fdb77)

2023-12-14 18:36 UTC, Mauroskyer approved these changes

2023-12-15 12:16 UTC, merged