JMV-3211-add-object-to-can-crete
janis-commerce/view-schema-validator pull request #289
Opened 2023-12-11 18:15 UTC by dgiannico19

## Link al ticket
- https://janiscommerce.atlassian.net/browse/JMV-3208
## Descripción del requerimiento
- Se requiere poder pasarle al `canCreate` ademas del booleano que aceptaba, un objeto con las propiedadaes `endpoint` y `endpointParameters`

## Descripción de la solución
- Se creó un modulo `can-create` que se utiliza en todos los lugres donde se usaba el canCreate para que ahora acepte en todos un objeto con `endpoint` y `endpointParameters`

## Cómo se puede probar?
- Corriendo los test a como dejo hoy, se agregaron test con nombre edit-with-canCreate-object yml y json con sus validadores en validator-test.js
- En los archivos tests/mocks/schemas/edit-with-canCreate-object.yml y tests/mocks/schemas/expected/edit-with.canCreate-object.json, probar enviando un string y el test debe romper, probar enviando un number y debe romper, en cambio con un objeto no deberia romper
- Tambien se puede probar otros validadores donde se utiliza el canCreate aplicando los objetos en su json y yml debería pasar sin problemas
Dejo YML
`canCreate:
      endpoint:
        service: service
        namespace: namespace
        method: method
        resolve: false
      endpointParameters:
        - name: status
          target: path
          value:
            dynamic: id
        - name: status
          target: query
          value:
            static: 1
        - name: status
          target: path
          value:
            dynamic: id
        - name: status
          target: query
          value:
            static: 1`
y JSON
`"canCreate": {
        "endpoint": {
          "service": "service",
          "namespace": "namespace",
          "method": "method",
          "resolve": false
        },
        "endpointParameters": [
          {
            "name": "status",
            "target": "path",
            "value": {
              "dynamic": "id"
            }
          },
          {
            "name": "status",
            "target": "query",
            "value": {
              "static": 1
            }
          },
          {
            "name": "status",
            "target": "path",
            "value": {
              "dynamic": "id"
            }
          },
          {
            "name": "status",
            "target": "query",
            "value": {
              "static": 1
            }
          }
        ]
      }`
## Link a la documentación
- Queda en el PR a Views

## Changelog
```
### Changed
- value to canCreate props
```

2023-12-12 01:01 UTC, Mauroskyer commented
Pasa todos los test probando como se indica en el Pr : 
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/a9dc7cdd-b368-4e28-96b0-f752088523a5)

Probando si rompe los test cuando no se arma bien el json o el yaml : 
![image](https://github.com/janis-commerce/view-schema-validator/assets/57736533/9542debd-e652-4c65-a838-0aadb59bbcfb)

2023-12-12 01:01 UTC, Mauroskyer approved these changes

2023-12-12 18:33 UTC, fiorafran requested changes

2023-12-12 18:33 UTC, fiorafran commented on lib/schemas/edit-new/modules/can-create.js
> +	oneOf: [
creo que lo mejor seria usar solamente la ref a la definicion de endpointParams

2023-12-12 18:37 UTC, fiorafran requested changes

2023-12-12 18:37 UTC, fiorafran commented on lib/schemas/browse/modules/filters/components/select.js
> +const getCanCreate = require('../../../../edit-new/modules/can-create');
capaz te conviene hacer una definicion en definition para no tener que importar asi. Y te queda mas bonito como el label prefix:
```labelPrefix: { $ref: 'schemaDefinitions#/definitions/stringPrefix' }```

2023-12-12 18:37 UTC, dgiannico19 commented on lib/schemas/edit-new/modules/can-create.js
> +	oneOf: [
Modificado!

2023-12-12 19:20 UTC, dgiannico19 commented on lib/schemas/browse/modules/filters/components/select.js
> +const getCanCreate = require('../../../../edit-new/modules/can-create');
Excelente, ahi lo pushee

2023-12-14 17:47 UTC, fiorafran requested changes

2023-12-14 17:47 UTC, fiorafran commented on lib/schemas/common/can-create.js
> +	]
asi como esta actualmente, me deja mandarle cualquier prop si es un objeto. Ejemplo:
canCreate:
 falopa: asd
 
 estaria bueno que cuando es objeto pida requerido endpoint y endpointParameters, y solo acepte estas dos props

2023-12-18 16:45 UTC, fiorafran approved these changes
Solucionado los temas hablados:
- Ya no acepta cualquier key cuando es objeto
- No rompe al pasar a true la key
- Toma el default al eliminar la key

2023-12-21 19:28 UTC, colomfernando approved these changes

2023-12-21 19:29 UTC, merged